---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Ensure the myapp Namespace exists.
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: app
        state: present

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        regcred: "{{ lookup('env','REGCRED') }}"

    - name: Ensure registry secret exists.
      kubernetes.core.k8s:
        state: present
        definition: 
          apiVersion: v1
          data:
            .dockerconfigjson: "{{ regcred }}"
          kind: Secret
          metadata:
            name: regcred
            namespace: app
          type: kubernetes.io/dockerconfigjson
    
    - name: Apply deployment.yml
      kubernetes.core.k8s:
        state: present
        src: manifests/deployment.yml
     



